Fix selection visuals for Godot 4 RC2
jarneson/godot-ply pull request #79
Opened 2023-02-18 13:44 UTC by MineBill

Opening this project in Godot 4 RC2 caused a bunch of changes in all of the import files, adding some new `high_quality` setting, so I separated them in a different commit.

It seems at some point `_edit` was changed so that it will give you a null variant to indicate that you are no longer selecting a valid object. I think it's better to reset the visibility of the selection there rather than `_make_visible` because:
 * `_make_visible` is called before `_edit`, so when selecting a PlyEditor node, `selection` is null (because it was reset by the last call to _edit) and as such we can't make it visible.
 * Docs recommend using `_edit` to clean up state when the variant is null.

I tested the changes with multiple `PlyEditor` nodes and everything seems to be working correctly.

2023-03-15 00:16 UTC, fire commented
Can you revise your pr on top of master? I think some things were broken by me.

2023-03-15 13:39 UTC, MineBill commented
Is this even needed now that you ported to Godot 4? I'll happily do it but I'm not at home right now. I would like however to do some other polish stuff and small fixes for stuff I've found. Do you want me to open new issues for them or just open pull requests?

2023-03-15 16:03 UTC, fire commented
It's up to you. Open issues if you are low on time, open pull requests if you can solve the issues.

2023-03-15 16:06 UTC, fire commented
addons/ply/plugin.gd is still outdated in master

2023-03-15 21:08 UTC, MineBill commented
Should be ready now!

2023-03-28 23:57 UTC, jarneson approved these changes

2023-03-28 23:58 UTC, jarneson commented on addons/ply/plugin.gd
> +		selection.selected = false
does this need a guard?

2023-03-29 00:00 UTC, jarneson requested changes

2023-03-29 00:00 UTC, jarneson commented on addons/ply/plugin.gd
> +	selection.selected = true
```suggestion
	if selection:
		selection.selected = false

	selection = o
```

2023-08-04 03:43 UTC, merged

2023-08-04 03:44 UTC, fire commented
Thanks